version: 2

sources:
  - name: dbt_sch
    schema: dbt_sch
    tables:
      - name: orders

models:
  - name: customer_sales
    columns:
      - name: customer_name
        tests:
          - not_null
      - name: total_spent
        tests:
          - not_null
